### ISSUE TITLE
An error with PGX server

### ISSUE THREAD

**Issue by khedersyria** [oracle/pgx-samples#16]
Hi Mr @rahul-tasker and every body
I am kheder I was using PGX server version 23.1 with no problems but when I changed this version to 23.4 I got this error result: "detail": "java.lang.AssertionError: accessing index: 2,192,673,758,255 that is out of bounds: [0, 1]" and When I ran this query "SELECT e FROM MATCH ()-[e]->() ON MYGRAPH LIMIT 10" where the limit was a small number, it gave me a correct result without any problem, but when I raised the limit to be 100 or 200, I got the problem shown in the following images.
Can you help me please?
![Capture](https://github.com/oracle-samples/pgx-samples/assets/126420061/47aef67d-2ead-49fd-b002-edbf6ef8f1b8)
![posman response](https://github.com/oracle-samples/pgx-samples/assets/126420061/5d7acc10-7270-499b-a835-158255d401b7)
![v1](https://github.com/oracle-samples/pgx-samples/assets/126420061/978b3d9a-3ebf-451e-9b4d-609680cdabb7)

**Comment by omsn** [comment]
This is a known bug in this PGX version. Fix is planned for 24.1 release. To work around this problem, either of the following should work

- add an `ORDER BY` to the query
- do not project vertices or edges in the SELECT clause, but only integers, longs, strings, etc.. For example: `SELECT id(e) FROM MATCH ()-[e]->() ON MYGRAPH`
