### ISSUE TITLE
PGX deployment question for Entity Linking

### ISSUE THREAD

**Issue by sgaetjen** [oracle/pgx-samples#2]
I've unzip the PGX 3.2.0 server zip file into the libs directory as the README indicates.

When I try to preprocess the graph, for example using

./gradlew runPreprocess --args="-g graph -i path/to/graph.json -p -n 100"

I am getting compileScala errors like this:

> Task :compileScala
Pruning sources from previous analysis, due to incompatible CompileSetup.
/u01/docker-custom/pgx-samples-master/entity-linking/src/main/scala/candidate_finder/CandidateFinder.scala:9: not found: object oracle
import oracle.pgx.api.{PgxGraph, VertexProperty}

I am not sure what to set to resolve this issue. I tried the CLASSPATH environment variable with lots of the PGX-related .jar files in it but could not get past this error

**Comment by martijndwars** [comment]
Judging from the [source code](https://github.com/oracle/pgx-samples/blob/aa287bdd6c213b2ce3dd18e2da777523bedf40e8/entity-linking/build.gradle#L6), the last person who worked on the Entity Linking example used PGX 19.2.0. Did you change this to PGX 3.2.0? Any chance you could upgrade to PGX 19.2.0?

(CC @rpatra, who is responsible for the Entity Linking example)

**Comment by sgaetjen** [comment]
Hi , I tried to run this with 19.3.1 and received the same error messages, thank you

**Comment by sgaetjen** [comment]
I just now deployed 19.2.0 and that seems to be running the pre-processor

**Comment by martijndwars** [comment]
Ok, closing this issue then. Please open a new ticket if something else pops up.
